name: Prime Focus Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85891
title: Prime Focus Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#000000'
    - '#6f6f6f'
    - '#494949'
    - '#bebebe'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
