name: Prime Focus Art
favicon: null
layout_spectrum: 0.8485758581664413
typography_spectrum: 0.24145301221869886
title: Prime Focus Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.22996326116845012
  lightness: 0.8730702127795666
  saturation: 0.7087799112778157
  rhythmicContrast: 0.041719895554706454
purpose: []
